name: Publish to NPM

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build

      - name: Authenticate with NPM
        run: npm login --registry=https://registry.npmjs.org/ --scope=@tbosmans --always-auth --auth-type=oauth --oauth-token=${{ secrets.NPM_AUTH_TOKEN }}

      - name: Publish to NPM
        run: npm publish --access public
